### Criar um novo Customer
POST http://localhost:3000/customers
Content-Type: application/json

{
  "name": "Carlos",
  "email": "calos@gmail.com",
  "password": "123456",
  "role": "customer",
  "phone_number": "+5599900101"
}

### Obter todos os Customers
GET http://localhost:3000/api/customers

### Obter um Customer pelo ID
# Substitua `1` pelo ID do Customer que você deseja obter
GET http://localhost:3000/customers/5

### Atualizar um Customer pelo ID
# Substitua `1` pelo ID do Customer que você deseja atualizar
PUT http://localhost:3000/customers/4
Content-Type: application/json

{
  "name": "Jane Doeew",
  "email": "jane.doewert@example.com",
  "password": "newpassword123",
  "role": "customer",
  "phone_number": "098-765-4321"
}

### Deletar um Customer pelo ID
# Substitua `1` pelo ID do Customer que você deseja deletar
DELETE http://localhost:3000/customers/4